### ISSUE TITLE
Simsilica Zone Library

### ISSUE THREAD

**Issue by jawaff** [Simsilica/SimEthereal#3]
Hello,

I've noticed that your zone implementation in SimEthereal is a bit newer than your Pager's zone implementation. I think it would help your libraries if you made SimEthereal dependent on the Pager library or even another more generic zone library. This would be necessary in order to allow libraries to utilize your zones in a way that didn't require the added network syncing.

For example, your IsoSurface library could potentially be integrated with SimEthereal in order to allow synchronization of smooth terrain. However, IsoSurface would probably be using SimEthereal's zone implementation unless there was some sort of adapter that IsoSurface defined. This would make IsoSurface then always dependent on a networking library even in the case of single player games.

**Comment by pspeed42** [comment]
The networking zones will almost always be different than the Pager's zones.  Moreover, the Pager supports nested zones at any level and SimEthereal networking does not.

Even though they share the idea of a grid, the two things are doing very different things.  One might concede that a centralized 'grid' idea would be nice... but that's why SimMath has the Grid class.  Neither SimEthereal (which probably could use it) nor Pager (which can't use it) use this class but it is available for applications to use for a Grid idea.

Even when physics is divided into zones, it's rare that it would coincide with SimEthereal zones... and the functionality is quite different anyway.

I'm going to close this.  If further compelling arguments can be made then feel free to reopen.
